<?php include("application/views/admin/common/header.php");?>
<?php include("application/views/admin/common/top_menu.php");?>

<div class="content">
	<div class="row">
		<div class="sixteen columns">
			<h1>The Astor Company Privacy Policy</h1>
		</div>
		<div class="row">
			<div class="sixteen columns">
				<p>The Astor Company is committed to maintaining your privacy and providing a valuable resource to you through this Web site. If you have any questions regarding the practices of The Astor Company to maintain your privacy, please contact the webmaster at <a href="mailto:info@astorrecycling.com">info@astorrecycling.com</a>. This Web site is administered by The Astor Company. The primary purpose of <a href="http://astorrecycling.com">astorrecycling.com</a> is to be a dynamic resource to help you navigate the complexities of business ownership transition. We want you to feel secure when visiting our site and are committed to maintaining your privacy when doing so. The following provides an overview of how we protect your privacy during your visit. Information on <a href="http://astorrecycling.com">astorrecycling.com</a> is gathered indirectly (for example, through our site's technology) and directly (for example, when you provide information on various pages of <a href="http://astorrecycling.com">astorrecycling.com</a>). One example of information we collect indirectly is through our Internet access logs. These logs are standard practice and critical to our ability to maintain a highly available Web site presence. When you access <a href="http://astorrecycling.com">astorrecycling.com</a>, your Internet address is automatically collected and is placed in our Internet access logs.</p>
				<h3>Use of information collected</h3>
				<p>Currently, we collect information directly from you through our Contact and In the News pages. This information we collect is submitted voluntarily to us by you. Information collected indirectly from you is intended to determine effective – and ineffective – components of our site, to help us identify ways to improve it, and eventually, to determine how we can tailor <a href="http://astorrecycling.com">astorrecycling.com</a> to make it a more beneficial experience to our visitors. Information collected directly (or voluntarily) from you is used solely for the intent expressed at the time of your submission of the information. In short, if we request your email address for contact information purposes, we will use it only for that purpose. You can expect that we will not use that information for any other purpose (unless expressly communicated), such as inclusion on an unsolicited email distribution list. The Astor Company will not sell individual information and will keep all direct information within The Astor Company. No information will be shared with outside parties without your express consent. The Astor Company will not collect sensitive personal data through this site. If we do seek to collect such data, we will ask you to consent to our proposed uses of the data through a Master Services Agreement, not part of this Web site. You are entitled to know whether we hold information about you and, if we do, to have access to that information and require it to be corrected if it is inaccurate. You can do this by contacting us via our webmaster at <a href="mailto:info@astorrecycling.com">info@astorrecycling.com</a>. We take appropriate steps to maintain the security of your data on <a href="http://astorrecycling.com">astorrecycling.com</a>. You should understand that the open nature of the Internet is such that data may flow over networks without security measures and may be accessed and used by people other than those for whom the data is intended. Currently, there are no functions or components of this Web site that require secure data transmission. In the event in the future that secure data is required, security and encryption will be employed.</p>
			</div>
		</div><!--// row -->
	</div><!--// row -->
</div><!--// content -->

<?php include("application/views/admin/common/footer.php");?>